# Generated by Django 5.0.7 on 2025-08-10 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountapp', '0003_alter_predictionresult_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('home_lat', models.FloatField()),
                ('home_lng', models.FloatField()),
                ('shift_start', models.TimeField(default='09:00')),
                ('shift_end', models.TimeField(default='18:00')),
                ('capacity_per_day', models.IntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='CleaningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('predicted_due', models.DateTimeField()),
                ('estimated_duration_min', models.IntegerField(default=20)),
                ('risk_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('done', 'Done')], default='pending', max_length=20)),
                ('window_start', models.DateTimeField(blank=True, null=True)),
                ('window_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='accountapp.draininfo')),
            ],
        ),
    ]
