# Generated by Django 5.0.7 on 2025-08-10 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningtask',
            name='assigned_crew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='maintenance.crew'),
        ),
        migrations.AddField(
            model_name='cleaningtask',
            name='scheduled_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cleaningtask',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
