# Generated by Django 5.0.7 on 2025-08-07 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrainInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100, verbose_name='시/도')),
                ('sub_region', models.CharField(max_length=100, verbose_name='구')),
                ('detail_region', models.CharField(max_length=100, verbose_name='동/리/도로명')),
                ('name', models.CharField(max_length=100, verbose_name='하수구 이름 또는 번호')),
                ('latitude', models.FloatField(verbose_name='위도')),
                ('longitude', models.FloatField(verbose_name='경도')),
            ],
            options={
                'verbose_name': '하수구 정보',
                'verbose_name_plural': '하수구 정보 목록',
                'db_table': 'DrainInfos',
                'unique_together': {('region', 'sub_region', 'detail_region', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='발송 시각')),
                ('alert_type', models.CharField(max_length=50, verbose_name='경고 유형')),
                ('recipient', models.CharField(max_length=100, verbose_name='수신자(관리자) 정보')),
                ('drain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountapp.draininfo', verbose_name='하수구 정보')),
            ],
            options={
                'verbose_name': '경고 로그',
                'verbose_name_plural': '경고 로그 목록',
                'db_table': 'AlertLogs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MotorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='작동 시간')),
                ('trigger_type', models.CharField(max_length=50, verbose_name='작동 트리거 유형')),
                ('drain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountapp.draininfo', verbose_name='하수구 정보')),
            ],
            options={
                'verbose_name': '모터 로그',
                'verbose_name_plural': '모터 로그 목록',
                'db_table': 'MotorLogs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='예측 시각')),
                ('predicted_risk_level', models.CharField(max_length=20, verbose_name='예측 위험도 (low, moderate, high)')),
                ('predicted_trash_height', models.FloatField(verbose_name='예측 쓰레기 높이 (cm)')),
                ('drain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountapp.draininfo', verbose_name='하수구 정보')),
            ],
            options={
                'verbose_name': '예측 결과',
                'verbose_name_plural': '예측 결과 목록',
                'db_table': 'PredictionResults',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SensorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='측정 시간')),
                ('sensor_type', models.CharField(max_length=50, verbose_name='센서 유형')),
                ('value', models.FloatField(verbose_name='측정 값 (cm, 유무 등)')),
                ('drain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountapp.draininfo', verbose_name='하수구 정보')),
            ],
            options={
                'verbose_name': '센서 로그',
                'verbose_name_plural': '센서 로그 목록',
                'db_table': 'SensorLogs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TrashStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('avg_height', models.FloatField(verbose_name='평균 쓰레기 높이 (cm)')),
                ('max_height', models.FloatField(verbose_name='최고 쓰레기 적재량 (cm)')),
                ('drain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountapp.draininfo', verbose_name='하수구 정보')),
            ],
            options={
                'verbose_name': '쓰레기 통계',
                'verbose_name_plural': '쓰레기 통계 목록',
                'db_table': 'TrashStats',
                'ordering': ['-date'],
            },
        ),
    ]
