# Generated by Django 5.0.7 on 2025-08-07 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='draininfo',
            unique_together={('region', 'sub_region', 'name')},
        ),
        migrations.RemoveField(
            model_name='draininfo',
            name='detail_region',
        ),
    ]
