# Generated by Django 5.0.7 on 2025-08-07 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_alter_draininfo_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predictionresult',
            options={'ordering': ['-date'], 'verbose_name': '예측 결과', 'verbose_name_plural': '예측 결과 목록'},
        ),
        migrations.RenameField(
            model_name='predictionresult',
            old_name='timestamp',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='predictionresult',
            old_name='predicted_trash_height',
            new_name='predicted_value',
        ),
    ]
