# Generated by Django 5.0.7 on 2025-09-11 11:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0003_alter_predictionresult_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorlog',
            name='trigger_type',
        ),
        migrations.AddField(
            model_name='motorlog',
            name='value',
            field=models.FloatField(default=1, verbose_name='측정 값 (cm, 유무 등)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='motorlog',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='작동 시간'),
        ),
    ]
