# Generated by Django 5.0.7 on 2025-09-11 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0004_remove_motorlog_trigger_type_motorlog_value_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MotorLog',
        ),
    ]
