# Generated by Django 5.0.7 on 2025-09-11 11:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0005_delete_motorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RainLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='측정 시간')),
                ('value', models.FloatField(verbose_name='측정 값 (cm, 유무 등)')),
                ('drain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountapp.draininfo', verbose_name='하수구 정보')),
            ],
            options={
                'verbose_name': '센서 로그',
                'verbose_name_plural': '센서 로그 목록',
                'db_table': 'rain',
                'ordering': ['-timestamp'],
            },
        ),
    ]
