# Generated by Django 5.0.7 on 2025-09-11 11:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0006_rainlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rainlog',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, null=True, verbose_name='측정 시간'),
        ),
        migrations.AlterField(
            model_name='sensorlog',
            name='timestamp',
            field=models.DateTimeField(null=True, verbose_name='측정 시간'),
        ),
    ]
